### ISSUE TITLE
projectile tweak

### ISSUE THREAD

**Issue by TheGrate1** [cactusbento/ULTRAUnNerf#2]
would it be possible to have auto aim be ignored when shooting cores/magnets?
find it hard to setup a saw trap in a horde of enemies

**Comment by cactusbento** [comment]
Ignore hostiles while still targeting coins/cores? 
If so, there are toggles for that. They are found under ImprovedAutoaim's toggle in the UltraTweaker menu.

Here's the behavior of the toggles:
https://github.com/cactusbento/ULTRAUnNerf/blob/7340858718631aff2ed0a128ef5f529e40d3393c/Tweaks/autoaimimproved.cs#L104-L108

Turn it off specifically when firing cores/magnets?
Probably not. At least not without some more drastic modifications on how autoaim works in ULTRAKILL. 

To be more specific, the scope of this mod is to just manipulate the target list of the autoaim system, not to not to modify the autoaim system overall. (It's already pretty good)

If a mod was to be made to address this use case, the following considerations would need to be addressed:
1. ULTRAKILL's built in autoaim has interpolated movement, meaning that the crosshair (and point of impact) will trace a line at a fixed speed from its previous position to the target position. You would need to change this behavior to be an instantaneous snap (Removing the interp component) in general or implement a special case just for firing cores and magnets (Adding special purpose logic along side the original autoaim).
2. Given the limitations of No. 1, you must also consider how the game knows when to snap the crosshair back to the center of the screen. For Core Eject, you would hook onto the +Attack2 and -Attack2 event/function. For Magnets (and other instant fires), this is harder since there is no time to slowly move the crosshair back to the center of the screen.

> find it hard to setup a saw trap in a horde of enemies

What you could do is to just reduce the size of the screen area that the autoaim uses and just go from there. That'll lower the chance of you shooting magnets into enemies.

**Comment by TheGrate1** [comment]
i had no idea there was interpolation, thanks for the explanation 
ill just git gud then
